import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  page: {
    padding: '32px 40px 60px',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 24,
    alignItems: 'flex-start',
    marginBottom: 24,
    flexWrap: 'wrap',
  },
  kicker: {
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    fontSize: 12,
    color: '#5b5b5b',
  },
  title: {
    fontSize: 40,
    margin: '8px 0 4px',
  },
  subtitle: {
    maxWidth: 480,
    color: '#4a4a4a',
    margin: 0,
  },
  selectCard: {
    background: '#fff',
    borderRadius: 16,
    padding: 16,
    boxShadow: '0 10px 30px rgba(15, 23, 42, 0.08)',
    minWidth: 280,
  },
  label: { display: 'block', fontSize: 12, color: '#6b6b6b', marginBottom: 6 },
  select: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid #e3e3e3',
    background: '#fff',
  },
  selectInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid #e3e3e3',
    background: '#fbfbfb',
  },
  checkboxGroup: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid #e3e3e3',
    background: '#fbfbfb',
    display: 'flex',
    gap: 12,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  checkboxOption: {
    display: 'inline-flex',
    gap: 6,
    alignItems: 'center',
    fontSize: 14,
    color: '#2b2b2b',
  },
  metaRow: {
    marginTop: 10,
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 12,
    color: '#666',
  },
  metaRowWide: {
    marginBottom: 12,
    display: 'flex',
    gap: 16,
    flexWrap: 'wrap',
    fontSize: 12,
    color: '#666',
  },
  error: {
    background: '#ffe8e5',
    color: '#9a2b19',
    padding: '10px 14px',
    borderRadius: 10,
    marginBottom: 16,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(320px, 1fr) minmax(320px, 1fr)',
    gap: 24,
  },
  panel: {
    background: '#ffffff',
    borderRadius: 18,
    padding: 20,
    boxShadow: '0 20px 40px rgba(15, 23, 42, 0.08)',
  },
  panelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  panelTitle: { margin: 0, fontSize: 20 },
  panelBadge: {
    background: '#f0f2ff',
    color: '#2d3fb8',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 12,
  },
  formGrid: {
    display: 'grid',
    gap: 10,
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    alignItems: 'start',
    marginBottom: 16,
  },
  input: {
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid #e3e3e3',
    background: '#fbfbfb',
  },
  primaryButton: {
    border: 'none',
    padding: '10px 14px',
    borderRadius: 10,
    background: '#1f2937',
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
  },
  ghostButton: {
    border: '1px solid #d8d8d8',
    padding: '8px 12px',
    borderRadius: 10,
    background: '#fff',
    cursor: 'pointer',
  },
  dangerButton: {
    border: '1px solid #f0b4a9',
    padding: '8px 12px',
    borderRadius: 10,
    background: '#fff5f3',
    color: '#b42318',
    cursor: 'pointer',
  },
  listHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 8,
  },
  listTitle: { margin: 0, fontSize: 16 },
  smallHint: { fontSize: 12, color: '#7a7a7a' },
  list: { display: 'grid', gap: 12 },
  listRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    padding: 12,
    borderRadius: 12,
    border: '1px solid #ededed',
    background: '#fcfcfc',
  },
  rowTitle: { fontWeight: 600 },
  rowMeta: { fontSize: 12, color: '#6f6f6f' },
  actionRow: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  editGrid: {
    display: 'grid',
    gap: 8,
    width: '100%',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
  },
  cardGrid: {
    display: 'grid',
    gap: 12,
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
  },
  card: {
    borderRadius: 14,
    padding: 14,
    background: 'linear-gradient(135deg, #fef6d8 0%, #f7f0ff 100%)',
    border: '1px solid #f2e5c7',
  },
  cardLabel: { fontSize: 12, color: '#6b5b2d' },
  cardValue: { fontSize: 22, fontWeight: 700, marginTop: 6 },
  tableHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
  },
  table: { width: '100%', borderCollapse: 'collapse', marginTop: 10 },
  th: {
    textAlign: 'left',
    borderBottom: '1px solid #e0e0e0',
    padding: 8,
    fontSize: 12,
    color: '#555',
  },
  td: { borderBottom: '1px solid #f0f0f0', padding: 8, fontSize: 14 },
};
