FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json tsconfig.base.json ./
COPY apps/event-service/package.json apps/event-service/package.json
RUN npm install

FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN cd apps/event-service && npm run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/apps/event-service/dist ./dist
CMD ["node","dist/apps/event-service/src/main.js"]
