FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json tsconfig.base.json ./
COPY apps/analytics-api/package.json apps/analytics-api/package.json
RUN npm install

FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm --workspace analytics-api run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/apps/analytics-api/dist ./dist
CMD ["node","dist/main.js"]
